### ISSUE TITLE
_.isEqual()

### ISSUE THREAD

**Issue by gsklee** [you-dont-need/You-Dont-Need-Lodash-Underscore#177]
Granted, I'd like to rid our project clean of Lodash stuff as you do, but as soon as I saw `_.isEqual()` usage I knew it's not gonna be straightforward. AFAIK there is still no easy way to do this even with ES2019 - or is there actually one? Please do add it into the README if it exists!

**Comment by stevemao** [comment]
@gsklee PR welcome

**Comment by cht8687** [comment]
@gsklee 

Yes, I think you are right. _.isEqual() compares a wide range of data structures.
From Lodash doc:
```js
This method supports comparing arrays, array buffers, booleans, date objects, error objects, maps, numbers, Object objects, regexes, sets, strings, symbols, and typed arrays. 
```

what is your special use case for this function? is it possible to simplify it based on the data structure of your project? for example, if they are just numbers or strings, we probably can narrow down to only compare certain types.

thoughts?

**Comment by jsjain** [comment]
Hello, @stevemao Can i take up this issue and submit a PR ?

**Comment by jsjain** [comment]
I have implemented this sample [isEqual gist](https://gist.github.com/jsjain/a2ba5d40f20e19f734a53c0aad937fbb) will this be fine ?

**Comment by cjtaylor1990** [comment]
@jsjain It still doesn't cover all cases that _.isEqual does. For example,

`let buffer = new ArrayBuffer(16);
let other = new ArrayBuffer(16);

console.log(isEqual(buffer,other));
console.log(_.isEqual(buffer,other));`

would print out:

`false
true`

I think this is likely going to be pretty difficult to be able to handle all possible cases without having a bloated function.

**Comment by jsjain** [comment]
yes, I implementation only covers common use cases, adding all cases would result in bloated function, should I go ahead on implement those or this would be ok, with readers note to use only for supported cases.

**Comment by cjtaylor1990** [comment]
@jsjain We'll see what the others say. @cht8687 @stevemao 

Personally, I think this may be a bit problematic. The issue is, if we would like to take your function and put it as an alternative in the rules file (./lib/rules/rules.json) for a new "isEqual" rule, then Eslinter is always going to pick up the use of _.isEqual, regardless of the use case, and then suggest the use of your function. If the user is not using it for the cases that your function covers, the suggestion doesn't work the the user is stuck with a linter telling them to change their code without giving a proper alternative.

That being said, I applaud you for taking up this particular issue and for the work you've done. I'm just thinking about the user experience and how to handle this rather complex issue.

**Comment by jsjain** [comment]
Thank you @cjtaylor1990 for the feedback, I completely agree with you, my idea was to just give a basic function in readme file, which would have been sufficient for most and inspiration for the rest.
